"""requirements-dev.txt <-> requirements-dev.lock drift guard (issue #39)."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "tools" / "check-lock-drift.py"
SPEC = importlib.util.spec_from_file_location("session_optimizer_lock_drift", SCRIPT)
drift = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(drift)


def test_real_lockfile_matches_real_txt():
    """The gate this module backs: run it on the actual repo files."""
    txt_pins = drift._parse_pins((ROOT / "requirements-dev.txt").read_text())
    lock_pins = drift._parse_pins((ROOT / "requirements-dev.lock").read_text())
    assert drift.find_drift(txt_pins, lock_pins) == []


def test_desynced_version_is_reported():
    txt_pins = {"ruff": "0.16.6", "pytest": "9.1.1"}
    lock_pins = {"ruff": "0.15.20", "pytest": "9.1.1"}
    problems = drift.find_drift(txt_pins, lock_pins)
    assert len(problems) == 1
    assert "ruff" in problems[0]
    assert "0.16.6" in problems[0]
    assert "0.15.20" in problems[0]


def test_pin_missing_from_lock_is_reported():
    txt_pins = {"coverage": "7.16.0"}
    lock_pins = {}
    problems = drift.find_drift(txt_pins, lock_pins)
    assert "absent from the lock" in problems[0]


def test_matching_pins_report_no_drift():
    pins = {"ruff": "0.16.6", "pytest": "9.1.1", "coverage": "7.16.0"}
    assert drift.find_drift(pins, dict(pins)) == []


def test_parse_pins_skips_comments_hashes_and_via_lines():
    text = (
        "# generated by uv\n"
        "ruff==0.16.6 \\\n"
        "    --hash=sha256:deadbeef\n"
        "    # via -r requirements-dev.txt\n"
        "\n"
        "pytest==9.1.1\n"
    )
    assert drift._parse_pins(text) == {"ruff": "0.16.6", "pytest": "9.1.1"}


def test_main_exits_nonzero_on_drift(tmp_path):
    txt = tmp_path / "requirements-dev.txt"
    lock = tmp_path / "requirements-dev.lock"
    txt.write_text("ruff==0.16.6\n")
    lock.write_text("ruff==0.15.20\n")
    assert drift.main([str(txt), str(lock)]) == 1


def test_main_exits_zero_when_current(tmp_path):
    txt = tmp_path / "requirements-dev.txt"
    lock = tmp_path / "requirements-dev.lock"
    txt.write_text("ruff==0.16.6\n")
    lock.write_text("ruff==0.16.6 \\\n    --hash=sha256:deadbeef\n")
    assert drift.main([str(txt), str(lock)]) == 0
