#!/bin/sh
# Generated by ~/.claude/hooks/_gate_resolve.py. This repo's gate: edit the checks below freely.
# Usage: scripts/gate.sh commit | push | verify [kind] | waive <gate> --reason "..."
# commit proves the staged tree (git write-tree); push proves HEAD's tree and reuses a green
# commit proof of the same tree. Proofs and failures: <git-common-dir>/zetetic-gates/.
# Exit: 0 green, 1 a check failed, 2 refused (tree differs from what is proven), 75 lock held.
set -u
TOP=$(git rev-parse --show-toplevel) || exit 2
cd "$TOP" || exit 2
COMMON=$(git rev-parse --git-common-dir) || exit 2
case "$COMMON" in /*) ;; *) COMMON="$TOP/$COMMON" ;; esac
PROOFS="$COMMON/zetetic-gates"
mkdir -p "$PROOFS" || exit 2

now() { date -u +%Y-%m-%dT%H:%M:%SZ; }
jesc() { tr '\n\r\t' '   ' | tr -d '\000-\010\013\014\016-\037' | sed 's/\\/\\\\/g; s/"/\\"/g'; }
tree_of() { if [ "$1" = commit ]; then git write-tree; else git rev-parse 'HEAD^{tree}'; fi; }
green() { [ -f "$1" ] && grep -q '"rc": 0' "$1" && grep -q "\"tree\": \"$2\"" "$1"; }

write_proof() { # kind tree cmd started
  tmp="$PROOFS/.$1-$2.$$"
  printf '{"tree": "%s", "head": "%s", "cmd": "%s", "rc": 0, "started": "%s", "finished": "%s", "host": "%s"}\n' \
    "$2" "$(git rev-parse HEAD 2>/dev/null)" "$(printf %s "$3" | jesc)" "$4" "$(now)" "$(hostname)" > "$tmp" &&
    mv "$tmp" "$PROOFS/$1-$2.json"
}

run_one() { # name argv...
  name=$1; shift
  echo "[gate:$name] $*"
  out=$(mktemp "${TMPDIR:-/tmp}/gate.XXXXXX")
  nice -n 10 env CARGO_BUILD_JOBS="${CARGO_BUILD_JOBS:-4}" RUST_TEST_THREADS="${RUST_TEST_THREADS:-4}" "$@" >"$out" 2>&1
  rc=$?
  if [ "$rc" -ne 0 ]; then
    rm -f "$PROOFS/$KIND-$TREE.json"
    printf '{"gate": "%s", "kind": "%s", "tree": "%s", "rc": %s, "excerpt": "%s", "time": "%s"}\n' \
      "$name" "$KIND" "$TREE" "$rc" "$(tail -c 800 "$out" | jesc)" "$(now)" >> "$PROOFS/failures.jsonl"
    echo "[gate:$name] ECHEC rc=$rc" >&2
    tail -n 40 "$out" >&2
    rm -f "$out"
    return 1
  fi
  rm -f "$out"
}

# The same checks as .github/workflows/ci.yml, on the hash-locked development
# requirements and the Python version CI uses.
run_dev() { # name argv...
  name=$1; shift
  run_one "$name" uv run --no-project --python 3.11 --with-requirements requirements-dev.txt "$@"
}

run_checks() {
  run_dev lint ruff check plugins tests tools || return 1
  run_dev format ruff format --check plugins tests tools || return 1
  run_dev test python -m pytest -q || return 1
}

CMD=$(cat <<'EOF_CHECKS'
ruff check plugins tests tools
ruff format --check plugins tests tools
python -m pytest -q
EOF_CHECKS
)

prove() {
  KIND=$1
  if [ "$KIND" = commit ]; then
    git diff --quiet || { echo "gate: refuse (code 2): fichiers suivis modifies mais non stages; git add d'abord." >&2; exit 2; }
  elif [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    echo "gate: refuse (code 2): arbre de travail modifie; commite ou stashe d'abord." >&2; exit 2
  fi
  TREE=$(tree_of "$KIND") || exit 2
  if green "$PROOFS/$KIND-$TREE.json" "$TREE"; then echo "deja prouve ($KIND, $TREE)"; return 0; fi
  if [ "$KIND" = push ] && green "$PROOFS/commit-$TREE.json" "$TREE"; then
    write_proof push "$TREE" "reuse commit proof" "$(now)" && echo "preuve push reprise de la preuve commit"
    return 0
  fi
  started=$(now)
  run_checks || exit 1
  write_proof "$KIND" "$TREE" "$CMD" "$started" && echo "preuve $KIND ecrite ($TREE)"
}

case "${1:-}" in
  commit|push)
    mkdir "$PROOFS/lock.d" 2>/dev/null || { echo "gate: un autre run tient $PROOFS/lock.d (supprime-le s'il est perime)" >&2; exit 75; }
    trap 'rmdir "$PROOFS/lock.d" 2>/dev/null' EXIT INT TERM
    prove "$1" ;;
  verify)
    kind=${2:-push}; TREE=$(tree_of "$kind") || exit 2
    green "$PROOFS/$kind-$TREE.json" "$TREE" || exit 2 ;;
  waive)
    [ "${3:-}" = "--reason" ] && [ -n "${4:-}" ] || { echo 'usage: scripts/gate.sh waive <gate> --reason "..."' >&2; exit 2; }
    printf '{"waive": "%s", "reason": "%s", "time": "%s"}\n' "$(printf %s "$2" | jesc)" "$(printf %s "$4" | jesc)" "$(now)" >> "$PROOFS/failures.jsonl"
    echo "derogation enregistree pour $2" ;;
  *) sed -n '2,7p' "$0" >&2; exit 2 ;;
esac
